<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1714225803681' stop='1714225829104'>
    <name>Login site CWI</name>
    <title>Login site CWI</title>
    <test-cases>
        <test-case start='1714225803708' status='passed' stop='1714225813604'>
            <name>Visualizar opção de recuperar senha esquecida</name>
            <title>Visualizar opção de recuperar senha esquecida</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1714225813637' status='broken' stop='1714225821305'>
            <name>Realizar login com dados inválidos (example #1)</name>
            <title>Realizar login com dados inválidos (example #1)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>cy.screenshot(...).then(...).catch is not a function</message>
                <stack-trace>TypeError: cy.screenshot(...).then(...).catch is not a function
                    at Context.eval (cypress/support/e2e.js:43:11)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1714225821365' status='broken' stop='1714225829100'>
            <name>Realizar login com dados inválidos (example #2)</name>
            <title>Realizar login com dados inválidos (example #2)</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>cy.screenshot(...).then(...).catch is not a function</message>
                <stack-trace>TypeError: cy.screenshot(...).then(...).catch is not a function
                    at Context.eval (cypress/support/e2e.js:43:11)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>