{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Test defects","children":[{"name":"The following error originated from your test code, not from Cypress.\n                \n                  > Cypress.Commands.on is not a function\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","children":[{"name":"An uncaught error was detected outside of a test","uid":"20fd0c6450c7e2bc","parentUid":"f909f5d02fb83b4a618084b04cb8e0ee","status":"broken","time":{"start":1714173562637,"stop":1714173562978,"duration":341},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"f909f5d02fb83b4a618084b04cb8e0ee"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}